name: CI

on: [push, pull_request]

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    # always run on push events, but only run on pull_request events when pull request pulls from fork repository
    # for pull requests within the same repository, the pull event is sufficient
    if: >
      github.event_name == 'push' ||
      github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name != github.repository

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # run your tests here, produce unit test result files in ./test-results/
      - name: Run test
        run: mvn test
        
      - name: Copy results
        run: mkdir test-results && cp target/*.jar test-results

      - name: Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        # the action is useless on pull_request events
        # (it can not create check runs or pull request comments)
        if: always() && github.event_name != 'pull_request'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          files: "test-results/*.xml"

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          path: test-results/*.xml
